src/blog/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from accounts.views import (login_view, register_view, logout_view)

urlpatterns = [
    #url(r'^$', 'newsletter.views.home', name='home'),
    url(r'^Home/', 'posts.views.home', name='home'),
    url(r'^contact/', 'posts.views.contact', name='contact'),
    url(r'^work/', 'posts.views.work', name='work'),
    url(r'^about/', 'posts.views.about', name='about'),
    url(r'^admin/', admin.site.urls),
    url(r'^comments/', include("comments.urls", namespace='comments')),
    url(r'^register/', register_view, name='register'),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^', include("posts.urls", namespace='posts')),
    # url(r'^(?P<slug>[\w-]+)/$', home, name='home'),
    # url(r'^posts/$', "<appname>.views.<function_name>"),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/posts/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import (
	post_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
	)

urlpatterns = [
	url(r'^$', post_list, name='list'),
    url(r'^create/$', post_create),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
    url(r'^contact/', 'posts.views.contact', name='contact'),
    url(r'^about/', 'posts.views.about', name='about'),
	url(r'^work/', 'posts.views.work', name='work'),
	url(r'^Home/', 'posts.views.home', name='home'),
    #url(r'^posts/$', "<appname>.views.<function_name>"),
]

src/posts/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.text import slugify
from django.forms.utils import flatatt

from markdown_deux import markdown
from comments.models import Comment
from .utils import get_read_time
# Create your models here.
# MVC MODEL VIEW CONTROLLER


#Post.objects.all()
#Post.objects.create(user=user, title="Some time")

class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        # Post.objects.all() = super(PostManager, self).all()
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())


def upload_location(instance, filename):
    #filebase, extension = filename.split(".")
    #return "%s/%s.%s" %(instance.id, instance.id, extension)
    PostModel = instance.__class__
    new_id = PostModel.objects.order_by("id").last().id + 1
    """
    instance.__class__ gets the model Post. We must use this method because the model is defined below.
    Then create a queryset ordered by the "id"s of each object, 
    Then we get the last object in the queryset with `.last()`
    Which will give us the most recently created Model instance
    We add 1 to it, so we get what should be the same id as the the post we are creating.
    """
    return "%s/%s" %(new_id, filename)

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location,
            null=True,
            blank=True,
            width_field="width_field",
            height_field="height_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    objects = PostManager()

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["-timestamp", "-updated"]

    def get_markdown(self):
        content = self.content
        markdown_text = markdown(content)
        return mark_safe(markdown_text)

    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

    if instance.content:
        html_string = instance.get_markdown()
        read_time_var = get_read_time(html_string)
        instance.read_time = read_time_var

pre_save.connect(pre_save_post_receiver, sender=Post)

src/posts/forms.py
from __future__ import unicode_literals
from django import forms

from pagedown.widgets import PagedownWidget
from django.forms.utils import flatatt
from .models import Post



import copy
import datetime
import re
from itertools import chain

from django.conf import settings
from django.forms.utils import flatatt, to_current_timezone

class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=False))
    publish = forms.DateField(widget=forms.SelectDateWidget)
    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "image",
            "draft",
            "publish",
        ]

src/posts/views.py
from __future__ import unicode_literals

try:
    from urllib import quote_plus  # python 2
except:
    pass

try:
    from urllib.parse import quote_plus  # python 3
except:
    pass

from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from comments.forms import CommentForm
from comments.models import Comment
from .forms import PostForm
from .models import Post


import copy
import datetime
import re
from itertools import chain

from django.conf import settings
from django.forms.utils import flatatt, to_current_timezone

def post_create(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404

    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        # message success
        messages.success(request, "Successfully Created")
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        "form": form,
    }
    return render(request, "post_form.html", context)


def post_detail(request, slug=None):
    instance = get_object_or_404(Post, slug=slug)
    if instance.publish > timezone.now().date() or instance.draft:
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404
    share_string = quote_plus(instance.content)

    initial_data = {
        "content_type": instance.get_content_type,
        "object_id": instance.id
    }
    form = CommentForm(request.POST or None, initial=initial_data)
    if form.is_valid() and request.user.is_authenticated():
        c_type = form.cleaned_data.get("content_type")
        content_type = ContentType.objects.get(model=c_type)
        obj_id = form.cleaned_data.get('object_id')
        content_data = form.cleaned_data.get("content")
        parent_obj = None
        try:
            parent_id = int(request.POST.get("parent_id"))
        except:
            parent_id = None

        if parent_id:
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs.exists() and parent_qs.count() == 1:
                parent_obj = parent_qs.first()

        new_comment, created = Comment.objects.get_or_create(
            user=request.user,
            content_type=content_type,
            object_id=obj_id,
            content=content_data,
            parent=parent_obj,
        )
        return HttpResponseRedirect(new_comment.content_object.get_absolute_url())

    comments = instance.comments
    context = {
        "title": instance.title,
        "instance": instance,
        "share_string": share_string,
        "comments": comments,
        "comment_form": form,
    }
    return render(request, "post_detail.html", context)


def post_list(request):
    today = timezone.now().date()
    queryset_list = Post.objects.active()  # .order_by("-timestamp")
    if request.user.is_staff or request.user.is_superuser:
        queryset_list = Post.objects.all()

    query = request.GET.get("q")
    if query:
        queryset_list = queryset_list.filter(
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(user__first_name__icontains=query) |
            Q(user__last_name__icontains=query)
        ).distinct()
    paginator = Paginator(queryset_list, 8)  # Show 25 contacts per page
    page_request_var = "page"
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)

    context = {
        "object_list": queryset,
        "title": "List",
        "page_request_var": page_request_var,
        "today": today,
    }
    return render(request, "post_list.html", context)


def post_update(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    form = PostForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "<a href='#'>Item</a> Saved", extra_tags='html_safe')
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        "title": instance.title,
        "instance": instance,
        "form": form,
    }
    return render(request, "post_form.html", context)


def post_delete(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    instance.delete()
    messages.success(request, "Successfully deleted")
    return redirect("posts:list")

def about(request):
	return render(request,"about.html", {})

def contact(request):
    return render(request,"contact.html",{})

def home(request):
	return render(request,"home.html", {})

def work(request):
	return render(request,"work.html", {})

src/templates/about.html
{% extends "base.html" %}



{% block content %}

<style>
{% block style %}
{% endblock %}
</style>


<div class="container">
            {% block jumbotron %}

            {% endblock %}

<div class="jumbotron">
 <div class="container">
	<div class="row">
<div class='row'>
    <div class='col-sm-6 text-align: left'>
        <p><h2><u>About</u></h2></p></br>
        <p>Hi and welcome to my blog.</p>
        <p>My name is Fulgence, I am an analyst and data science enthusiast based in London. </p>
        <p>I write about real estate and cities, data mining, Python and Django programming.</p>
        <p>That's the plan, which also means an endless list of interests ranging from ice fishing, photography, basketball or food will have to be kept at bay and away from these pages!</p>
        <p>This site was hand-coded with <b>Django </b>, a web development framework based on <b>Python</b>, thanks to numerous open-source, online learning resources.</p></section></br></br></br>
    </div>
    <div class="col-sm-6 text-align right">
         <p><h2><u> </u></h2></p></br>
        <p><h2><u> </u></h2></p></br>
          <img  src="http://www.sunipix.com/Office%20Buildings-1.jpg" width="460" height="345" class="img-responsive">
    </div>
</div>

</div>
</div>
	</div>
</div>
</div>
</section>
</section>
 <div class="row">
							<div class="3u 12u(mobile)">

							</div>
</div>

</div>

<div class='row'>
</div>

{% endblock %}

src/templates/base.html
{% load staticfiles %}
<!--DOCTYPE html -->
<html>
<head>
<title>{% block head_title %} RS & A {% endblock head_title %}</title>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet"/>
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css' >
<!-- social buttons icons -->


<link rel='stylesheet' href='{% static "css/base.css" %}' />
<style>
{% block style %}{% endblock style %}
</style>

{% block head_extra %} {% endblock head_extra %}
</head>
<body>

{%  include 'navbar.html' %}

<div class="container">
            {% block jumbotron %}

            {% endblock %}

 </div> <!-- /container -->

<div id="fb-root"></div>
<script>(function(d, s, id) {
var js, fjs = d.getElementsByTagName(s)[0];
if (d.getElementById(id)) return;
js = d.createElement(s); js.id = id;
js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";
fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


{% block content %}{% endblock content %}



<!-- Latest compiled and minified JavaScript -->
<script   src="http://code.jquery.com/jquery-1.12.2.min.js"   integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk="   crossorigin="anonymous"></script>


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

<script src='https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js'></script>

<script type="text/javascript">
$(document).ready(function(){
    $(".content-markdown").each(function(){
            var content = $(this).text()
            console.log(content)
            var markedContent = marked(content)
            console.log(markedContent)
            $(this).html(markedContent)
    })
    $(".content-markdown img").each(function(){
            $(this).addClass("img-responsive");
    })
})

    var contentInput = $("#id_content");
    function setContent(value){
        var markedContent = marked(value)
        $("#preview-content").html(markedContent)

        $("#preview-content img").each(function(){
            $(this).addClass("img-responsive")
        })
    }
    setContent(contentInput.val())
    contentInput.keyup(function(){
        var newContent = $(this).val()
        setContent(newContent)
    })
    var titleInput = $("#id_title");

    function setTitle(value) {
        $("#preview-title").text(value)
    }
    setTitle(titleInput.val())
    titleInput.keyup(function(){
        var newContent = $(this).val()
        setTitle(newContent)
    })
    $(".comment-reply-btn").click(function(event){
        event.preventDefault();
        $(this).parent().next(".comment-reply").fadeToggle();
    })
</script>


       <!--<footer class="bd-footer text-muted">
          <div class="copyrights">
            <p>&copy;2017 <a href="{% url 'work' %}" target="_blank"> Research, Strategy & Analytics</a></p>
          </div><!--copyrights -->
<footer>
<div id="footer">
  <div class="container text-center">
  </div>
</div>
</footer>

<!-- Footer Wrapper -->
				<div id="footer-wrapper">
					<footer id="footer" class="container text-center">
						<div class="row">
							<div class="3u 12u(mobile)">

							</div>
							<div class="3u 12u(mobile)">

							</div>
							<div class="6u 12u(mobile)">
							<div class="container">
            <a href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}&title={{ instance.title }}&summary={{ share_string }}&source={{ request.build_absolute_uri }}" target="blank" class="fa fa-linkedin"></a> | <a href="https://twitter.com/home?status={{ instance.content|truncatechars:80 }}%20{{ request.build_absolute_uri }}" target="blank" class="fa fa-twitter"></a> | <a href="https://plus.google.com/share?url={{ request.build_absolute_uri }}" class="fa fa-google-plus"></a>
		</div>
				</div>
							<div class="6u 12u(mobile)">

								<!-- Contact -->
									<br>
								<a type="button" class="btn btn-sm btn-primary" href="{% url 'work' %}" value="Input Button" role="button">Get in touch &raquo;</a>
									 </br>
								<div>
											<div class="row">
												<div class="6u 12u(mobile)">
												</div>
												 <br class="footer">


												<div class="6u 12u(mobile)">
													<dl class="contact">
														<dt><u>Email:</u></dt>
														<dd><a href="#">kayiranga@gmail.com</a></dd></br>
														</dd>
														<dt><u>Tel:</u></dt>
														<dd>(44) 07947 197 008</dd>
													</dl>
												</div>
											</div>
										</div>
									</section>

							</div>
						</div>
						<div class="row">
							<div class="12u">
								<div id="copyright text-center">
									<ul class="menu">
										<li><a href="{% url 'work' %}">&copy; Research, Strategy & Analytics</a></li>
									</ul>
								</div>
							</div>
						</div>
					</footer>
				</div>

		</div>

		<!-- Scripts -->

			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/jquery.dropotron.min.js"></script>
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/skel-viewport.min.js"></script>
			<script src="assets/js/util.js"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="assets/js/main.js"></script>

</body>

</html>

src/templates/comment_thread.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}


{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}



{% block content %}
{{ object }}



<div class='col-sm-6 col-sm-offset-3'>


          <p>{{ comment.content }}</p>
          <footer>via {{ comment.user }} | {{ comment.timestamp|timesince }} ago | {% if comment.children.count > 0 %}{{ comment.children.count }} Comment{% if comment.children.count > 1 %}s{% endif %} {% endif %} {% if request.user == comment.user %}<a href='{{ comment.get_delete_url }}'>Delete</a> {% endif %}</footer>
          <hr/>
          <div>
              {% for child_comment in comment.children %}
                <blockquote>
                <p>{{ child_comment.content }}</p>
                <footer>via {{ child_comment.user }} | {{ child_comment.timestamp|timesince }} ago | {% if request.user == child_comment.user %}<a href='{{ child_comment.get_delete_url }}'>Delete</a>{% endif %}</footer>
                </blockquote>
             {% endfor %}
             {% if request.user.is_authenticated %}
            <form method="POST" action="."> {% csrf_token %}
                {{ form|crispy }}
                <input type='hidden' name='parent_id' value='{{ comment.id }}'>
                <input type='submit' value='Reply' class='btn btn-default'>
            </form>
            {% else %}
            <p>You must login to comment </p>
            {% endif %}
        </div>



        <hr/>
</div>


{% endblock content %}

src/templates/confirm_delete.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}


{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}



{% block content %}

<div class='col-sm-6 col-sm-offset-3'>
  <h1>Confirm Delete</h1>


            <form method="POST" action="."> {% csrf_token %}
                <p>A re you sure you want to delete: "{{ object.content }}"?</p>

                <input type='submit' value='Confirm' class='btn btn-warning'>
                <a href='{{ object.get_absolute_url }}' class='btn btn-default'>Cancel</a>
            </form>
        </div>



        <hr/>
</div>


{% endblock content %}

src/templates/contact.html
{% extends "base.html" %}



{% block content %}

<div class='row'>
<div class='col-sm-6 col-sm-offset-3 text-center'>
<h2><u>Contact: </u></h2>
<p>Tel: 44(0)7947 197 008</p>
<p>E-mail: kayiranga@gmail.com </p>

</div>

</div>


{% endblock %}

src/templates/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class='col-sm-6 col-sm-offset-3'>
<h1>{{ title }}</h1>


<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form|crispy }}
<input type='submit' class='btn btn-default' value='{{ title }}' />
</form>
</div>
{% endblock content %}

src/templates/home.html
{% extends "base.html" %}
{% load crispy_forms_tags %}



{% block head_title %}Welcome | {{ block.super }}{% endblock %}

<style>
{% block style %}
{% endblock %}
</style>
{% block content %}

<div class="container">
            {% block jumbotron %}

            {% endblock %}

<div class="jumbotron">
 <div class="container">
	<div class="row">
		<p class='col-sm-6 col-sm-offset-3'>
        <h2><strong>Hi! Welcome to my blog.</strong></h2>
        <p>I write on real estate and cities, data science and Python programming.
           Yes, you read it right, after all one has to accept that their interests on such vital subjects as food,
           photography or basketball are not that keenly shared by fellow web surfers! How does one know?
           You may wish to ask. Well... <i><b>the data speaks for itself.</b></i> Or does it? Let's try to find out.</p>
		<p>
		<a class="btn btn-lg btn-primary" href="{% url 'posts:list' %}" role="button">Read more &raquo;</a>
		</p>
		<iframe width="560" height="315" position="center" src="https://www.youtube.com/embed/4Jec_8S4BnE" frameborder="0" allowfullscreen></iframe>
        </div>
	</div>
</div>
</div>




<h1></h1>

	<h2></h2>
	<table class='table'>

<div class="row">


	<div class='col-sm-3'>
<p class='lead text-align-center'></p>
</div>

</div>

{% endblock %}

src/templates/messages_display.html
 {% if messages %}
    <div class='messages'>

    <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>
    {% endfor %}
    </ul>

    </div>
{% endif %}

src/templates/navbar.html
<div class="navbar-wrapper">
  <div class="container">
    <nav class="navbar navbar-inverse">
      <!-- and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">Home</a>
    </div>
{% block post_detail_link %}
        {% endblock %}
    <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'posts:list' %}">Blog</a></li>
            <form class="navbar-form navbar-left">
                <div class="form-group">
                <input class='form-control' type='text' name='q' placeholder='Search this website...' value='{{ request.GET.q }}'/>
                    <!-- <input class='btn btn-default' type='submit' value='Search' /> -->
                 <button class='btn btn-default' type='submit'>Search <i class="fa fa-search"></i></button>
                </div>
            </form>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sector Analytics <b class="caret"></b></a>
          <ul class="dropdown-menu inverse">
            <li><a href="{% url 'posts:list' %}">Housing & CRE</a></li>
            <li><a href="{% url 'posts:list' %}">Retail & Leisure</a></li>
            <li><a href="{% url 'posts:list' %}">Cities & Infrastructure</a></li>
          </ul>
        </li>
          </li>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">About<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'work' %}">Work with us</a></li>
          </ul>
        </li>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Resources<b class="caret"></b></a>
          <ul class="dropdown-menu inverse">
            <li><a href="#">Book Reviews</a></li>
            <li><a href="#">Data Science & Machine Learning</a></li>
            <li><a href="#">Programming</a></li>
          </ul>
         </li>
         {% if not request.user.is_authenticated %}
        <li class='pull-right'><a href='{% url "register" %}'>Register</a></li>
        <li class='pull-right'><a href='{% url "login" %}'>Login</a></li>
        {% else %}
        <li class='pull-right'><a href='{% url "logout" %}'>Logout</a></li>
        {% endif %}
        </ul>
      </div>
    </nav>
  </div><!-- /.container -->
</div><!-- /.navbar-wrapper -->

src/templates/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_extra %}
{{ form.media }}

{% endblock head_extra %}



{% block content %}
<div class='col-sm-6'>
<h1>Preview</h1>
<hr/>
<div class='content-preview'>
    <h3 id='preview-title'></h3>
    <p id='preview-content'></p>
</div>
</div>
<div class='col-sm-6'>
<h1>Form</h1>
<hr/>

<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form|crispy }}
<input type='submit' class='btn btn-default' value='Create Post' />
</form>
</div>
{% endblock content %}